{% set name = "ipyreact" %}
{% set version = "0.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ipyreact-{{ version }}.tar.gz
  sha256: a74b9f61176ca75c1c80ccfc46c35a7ad5591a30612d0e1e6fdbf91549fbf6a6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - hatchling >=1.3.1
    - hatch-jupyter-builder >=0.3.2
    - jupyterlab ==3.*
    - pip
  run:
    - python >=3.7
    - ipywidgets >=7.0.0
    - anywidget >=0.2.0

test:
  imports:
    - ipyreact
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/widgetti/ipyreact
  summary: React for ipywidgets that just works
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - kolibril13
    - maartenbreddels
    - martinRenou
